apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-gateway-svc
  name: api-gateway-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: api-gateway
  type: LoadBalancer