apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-gateway-svc
  name: api-gateway-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: api-gateway